/**
 * WS6 M9 — `script` transport. Generates a bash (linux/macos) or
 * pwsh (windows) install script the operator runs themselves on the
 * target host. No remote exec from Signalman; lowest-risk transport.
 *
 * Useful when:
 *   - The operator doesn't want to expose SSH/WinRM credentials to
 *     Signalman.
 *   - The target is an air-gapped environment that requires a
 *     human-driven install step.
 *   - The runner needs to be installed alongside other operator-
 *     specific bootstrap (the script can be edited / extended).
 *
 * The emitted script:
 *   1. Downloads the runner binary from `binary.url`
 *   2. Optionally verifies sha256
 *   3. Writes the runner.yaml registration file
 *   4. Starts the runner (systemctl / launchctl / sc.exe / docker run)
 */

import { promises as fsp } from "node:fs";
import { resolveExpectedSha256 } from "./binary.js";
import type {
  BootstrapCommonOptions,
  BootstrapResult,
  RunnerDeployTransport,
  ScriptTransportOptions,
  TransportExec,
  TransportOptions,
} from "./transport.js";

function shellEscape(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

function pwshEscape(s: string): string {
  return `'${s.replace(/'/g, `''`)}'`;
}

function emitBashScript(
  common: BootstrapCommonOptions,
  expectedSha: string | null,
): string {
  const url = shellEscape(common.binary.url);
  const cpUrl = shellEscape(common.controlPlaneUrl);
  const token = shellEscape(common.token);
  const workerName = shellEscape(common.workerName);
  const shaCheck = expectedSha
    ? `actual="$(sha256sum /usr/local/bin/signalman-runner | awk '{print $1}')"\nif [ "$actual" != ${shellEscape(expectedSha)} ]; then\n  echo "sha256 mismatch: expected ${expectedSha}, got $actual" >&2\n  exit 1\nfi`
    : `echo "(sha256 not pinned; skipping verification)" >&2`;
  return [
    `#!/usr/bin/env bash`,
    `# Generated by signalman runner deploy --transport script`,
    `# Worker name: ${common.workerName}`,
    `# Runner binary: ${common.binary.url}`,
    `set -euo pipefail`,
    ``,
    `echo "[signalman] downloading runner binary..."`,
    `curl -fsSL ${url} -o /usr/local/bin/signalman-runner`,
    `chmod +x /usr/local/bin/signalman-runner`,
    ``,
    shaCheck,
    ``,
    `echo "[signalman] writing runner config..."`,
    `mkdir -p ~/.signalman`,
    `cat > ~/.signalman/runner.yaml <<EOF`,
    `control_plane_url: ${common.controlPlaneUrl}`,
    `token: ${common.token}`,
    `worker_name: ${common.workerName}`,
    `EOF`,
    `chmod 0600 ~/.signalman/runner.yaml`,
    ``,
    `echo "[signalman] starting runner..."`,
    `/usr/local/bin/signalman-runner start \\`,
    `  --control-plane ${cpUrl} \\`,
    `  --token ${token} \\`,
    `  --worker-name ${workerName} &`,
    ``,
    `echo "[signalman] runner '${common.workerName}' started in background"`,
    ``,
  ].join("\n");
}

function emitPwshScript(
  common: BootstrapCommonOptions,
  expectedSha: string | null,
): string {
  const url = pwshEscape(common.binary.url);
  const cpUrl = pwshEscape(common.controlPlaneUrl);
  const token = pwshEscape(common.token);
  const workerName = pwshEscape(common.workerName);
  const shaCheck = expectedSha
    ? `$actual = (Get-FileHash -Algorithm SHA256 "C:\\Program Files\\Signalman\\signalman-runner.exe").Hash.ToLower()\nif ($actual -ne ${pwshEscape(expectedSha)}) {\n  Write-Error "sha256 mismatch: expected ${expectedSha}, got $actual"\n  exit 1\n}`
    : `Write-Host "(sha256 not pinned; skipping verification)"`;
  return [
    `# Generated by signalman runner deploy --transport script`,
    `# Worker name: ${common.workerName}`,
    `# Runner binary: ${common.binary.url}`,
    `$ErrorActionPreference = 'Stop'`,
    ``,
    `Write-Host "[signalman] downloading runner binary..."`,
    `New-Item -ItemType Directory -Force -Path "C:\\Program Files\\Signalman" | Out-Null`,
    `Invoke-WebRequest -Uri ${url} -OutFile "C:\\Program Files\\Signalman\\signalman-runner.exe"`,
    ``,
    shaCheck,
    ``,
    `Write-Host "[signalman] writing runner config..."`,
    `New-Item -ItemType Directory -Force -Path "$env:USERPROFILE\\.signalman" | Out-Null`,
    `Set-Content -Path "$env:USERPROFILE\\.signalman\\runner.yaml" -Value @"`,
    `control_plane_url: ${common.controlPlaneUrl}`,
    `token: ${common.token}`,
    `worker_name: ${common.workerName}`,
    `"@`,
    ``,
    `Write-Host "[signalman] starting runner..."`,
    `Start-Process -FilePath "C:\\Program Files\\Signalman\\signalman-runner.exe" \``,
    `  -ArgumentList @('start', '--control-plane', ${cpUrl}, '--token', ${token}, '--worker-name', ${workerName})`,
    ``,
    `Write-Host "[signalman] runner '${common.workerName}' started"`,
    ``,
  ].join("\n");
}

export class ScriptTransport implements RunnerDeployTransport {
  readonly kind = "script" as const;

  async bootstrap(
    common: BootstrapCommonOptions,
    opts: TransportOptions,
    _exec: TransportExec,
  ): Promise<BootstrapResult> {
    if (opts.kind !== "script") {
      throw new Error(`ScriptTransport.bootstrap: opts.kind must be 'script' (got ${opts.kind})`);
    }
    const o = opts as ScriptTransportOptions;
    const expectedSha = resolveExpectedSha256(common.binary);
    const script =
      o.os === "windows"
        ? emitPwshScript(common, expectedSha)
        : emitBashScript(common, expectedSha);

    if (o.outputPath) {
      await fsp.writeFile(o.outputPath, script, "utf-8");
      if (o.os !== "windows") {
        // bash scripts: chmod +x so the operator can just run them.
        await fsp.chmod(o.outputPath, 0o755);
      }
    }

    return {
      transport: "script",
      workerName: common.workerName,
      script,
      detail: {
        os: o.os,
        bytes: script.length,
        outputPath: o.outputPath ?? null,
        sha256_pinned: expectedSha !== null,
      },
    };
  }
}
