/**
 * `signalman init` — scaffold a new Signalman project (P9.3).
 *
 * Locked design (per ROADMAP P9.3):
 *
 *   - **Minimal default.** Creates `.signalman/{config.yaml,
 *     scenarios/,templates/}` plus a sample scenario. Runs in <1s.
 *     No network calls, no cert generation, no VM creation. Safe to
 *     re-run.
 *
 *   - **`--bootstrap` opt-in.** Reserved for the interactive bootstrap
 *     flow (cert generation, base-image fetch, VM provision).
 *     Reserved here as a flag check + descriptive "not yet
 *     implemented" message — the flag's existence pins the future
 *     surface so docs and tests can refer to it. P9.5 (template
 *     fetch) and P9.1 (provision) compose into this once they land.
 *
 *   - **`--force` to overwrite existing scaffolding.** Default is
 *     fail-with-explanation when `.signalman/` already exists. We do
 *     NOT silently merge — that risks clobbering operator edits.
 *
 *   - **No prompts in the default path.** Both human and LLM operators
 *     drive `init` non-interactively. Bootstrap will prompt; default
 *     init will not.
 *
 * The verb is intentionally split from the rest of the verbs/ module
 * because it's the only one that *creates* state on disk rather than
 * reading it — a different threat surface (file writes outside cwd
 * are refused) and a different testing shape (filesystem doubles).
 */

import * as fs from "node:fs";
import * as path from "node:path";

/** Inputs to `runInit`. Matches both CLI args and MCP `signalman_init` tool input. */
export interface InitParams {
  /** Target directory for the scaffold. Defaults to cwd. */
  cwd?: string;
  /** When true, overwrites existing `.signalman/` content. Default false. */
  force?: boolean;
  /**
   * Reserved for the interactive bootstrap flow (cert gen + template
   * fetch + VM provision). v0.1.1 surfaces the flag but emits a
   * descriptive "not yet implemented" message so the surface stays
   * pinned.
   */
  bootstrap?: boolean;
  /** Project name written into config.yaml. Default: directory basename. */
  projectName?: string;
}

/** Result envelope for `runInit`. Matches the verb-result shape used elsewhere. */
export interface InitResult {
  /** Absolute path of the project root (the directory containing `.signalman/`). */
  projectRoot: string;
  /** Absolute paths of files actually written this invocation. */
  filesCreated: string[];
  /** Files that already existed and were left untouched (only when `force=false`). */
  filesSkipped: string[];
  /** When `bootstrap=true`, the next-step instruction printed to stderr. */
  bootstrapDeferredMessage?: string;
}

/** Path of every file the scaffold lays down, relative to the project root. */
interface ScaffoldEntry {
  relPath: string;
  content: string;
  /** When true, the file is created with `0o755` so it's executable. */
  executable?: boolean;
}

/**
 * The minimal scaffold. Kept inline (not as an external resource) so
 * `signalman init` works even when run from a packaged binary that
 * doesn't carry node_modules or assets.
 *
 * Each entry's content is exactly what lands on disk — operators
 * can `diff` against this constant to spot drift. When you change
 * the scaffold, bump the version comment in the generated config so
 * we can tell which version of `init` produced an existing layout.
 */
function scaffoldEntries(projectName: string): ScaffoldEntry[] {
  return [
    {
      relPath: ".signalman/config.yaml",
      content: configYaml(projectName),
    },
    {
      relPath: ".signalman/scenarios/.gitkeep",
      content: "",
    },
    {
      relPath: ".signalman/templates/.gitkeep",
      content: "",
    },
    {
      relPath: ".signalman/scenarios/sample/setup.yaml",
      content: sampleSetupYaml(),
    },
    {
      relPath: ".signalman/scenarios/sample/assertions.yaml",
      content: sampleAssertionsYaml(),
    },
    {
      relPath: ".signalman/scenarios/sample/workflow.md",
      content: sampleWorkflowMd(),
    },
  ];
}

function configYaml(projectName: string): string {
  return `# Signalman project config (created by \`signalman init\`).
#
# Schema version: 1
# Generated by signalman init (P9.3 layout, 2026-04-28).
#
# This file holds defaults that apply to every scenario in this
# project. Per-scenario overrides go in each scenario's setup.yaml.

apiVersion: signalman.dev/v1alpha1
kind: ProjectConfig
metadata:
  name: ${JSON.stringify(projectName)}

# Default hypervisor backend. Override per-scenario via vms[].backend.
# Supported: hyperv (Windows), tart (macOS), vmware (cross-platform).
hypervisor: hyperv

# Per-template defaults are read from .signalman/templates/<name>.yaml
# (see \`signalman init --bootstrap\` for managed defaults; or copy
# from the project's examples/ directory).

# Optional: relative path to the project's bundle manifests directory.
# Bundles drive \`signalman vm install-bundle\` and the scenario
# \`software:\` key (P9.2). Default: bundles/.
bundles_dir: bundles

# Optional: opt out of the legacy layout deprecation warning. Most
# new projects don't need this.
suppress_legacy_warning: false
`;
}

function sampleSetupYaml(): string {
  return `# Sample scenario — created by \`signalman init\`.
#
# This scenario is a no-op smoke test that verifies the runner can
# load + dispatch a scenario without creating a VM. Replace with your
# own setup once you've provisioned a guest agent (\`signalman vm
# provision\`).

name: "sample: signalman is wired up"
version: "1.0"
tags: ["smoke", "init-sample"]

# No VMs declared — this scenario asserts purely on the host.
vms: []

# Setup steps run sequentially before assertions. Empty = nothing to
# do. Real scenarios use vm_copy_file, vm_run_command, vm_install,
# install_bundle (P9.2), etc.
setup: []
`;
}

function sampleAssertionsYaml(): string {
  return `# Sample scenario assertions — created by \`signalman init\`.
#
# Assertions are the pass/fail gates of a scenario. The sample below
# always passes (host_command \`echo hello\` exits 0); replace with
# real checks against the VMs your scenario stands up.

assertions:
  - kind: host_command
    command: ["node", "-e", "process.stdout.write('hello\\\\n')"]
    expect:
      exit_code: 0
      stdout_contains: "hello"
`;
}

function sampleWorkflowMd(): string {
  return `# Sample scenario workflow

This is a no-op smoke test. It verifies that:

1. \`signalman list\` finds this scenario.
2. \`signalman plan sample\` parses without error.
3. \`signalman run sample\` produces a pass envelope.

Replace this narrative with your own workflow once you've provisioned
a real guest VM with \`signalman vm provision\`.

## Adapting this scenario

When you're ready to validate against a real VM:

1. Run \`signalman vm provision endpoint-1 --template win11-base\`
   (creates the VM, installs the guest agent, takes the
   \`agent-installed\` checkpoint).
2. Replace \`vms: []\` in \`setup.yaml\` with the VM definition (see
   examples/ in the Signalman repo for reference).
3. Add real \`setup:\` steps (e.g. \`vm_install\`, \`vm_run_command\`).
4. Add real \`assertions:\` (e.g. \`process_status\`, \`file_access\`).
5. Re-run \`signalman run <scenario>\` and iterate.
`;
}

// ── Implementation ────────────────────────────────────────────────

const BOOTSTRAP_DEFERRED = `\
--bootstrap is reserved for v0.1.1's interactive bootstrap flow. It
will compose:
  1. signalman vm fetch-template <name>          (P9.5)
  2. dev cert generation (scripts/generate-dev-certs.ps1)
  3. signalman vm provision <name>               (P9.1)

Until P9.1 + P9.5 land, run those steps manually after \`signalman
init\` completes. See ROADMAP.md > P9 (v0.1.1) for status.`;

/**
 * Scaffold a Signalman project. Pure-ish: filesystem writes are
 * confined to `params.cwd ?? process.cwd()`; no network, no
 * subprocess.
 *
 * Idempotency: with `force=false` (the default) any pre-existing
 * file is left alone and reported in `filesSkipped`. With `force=true`
 * existing files are overwritten.
 */
export function runInit(params: InitParams = {}): InitResult {
  const cwd = path.resolve(params.cwd ?? process.cwd());
  const projectName = params.projectName ?? path.basename(cwd);
  const force = !!params.force;

  // Validate projectName so it doesn't carry shell metachars or path
  // separators into config.yaml. We don't sanitize — we refuse, so
  // operators see the failure rather than silently mangled output.
  if (!isSafeProjectName(projectName)) {
    throw new Error(
      `signalman init: projectName ${JSON.stringify(projectName)} contains ` +
        `characters not allowed (only alphanumerics, dot, dash, underscore, space).`,
    );
  }

  const filesCreated: string[] = [];
  const filesSkipped: string[] = [];

  for (const entry of scaffoldEntries(projectName)) {
    const abs = path.join(cwd, entry.relPath);
    if (fs.existsSync(abs) && !force) {
      filesSkipped.push(abs);
      continue;
    }
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, entry.content, { mode: entry.executable ? 0o755 : 0o644 });
    filesCreated.push(abs);
  }

  const result: InitResult = {
    projectRoot: cwd,
    filesCreated,
    filesSkipped,
  };

  if (params.bootstrap) {
    result.bootstrapDeferredMessage = BOOTSTRAP_DEFERRED;
  }

  return result;
}

/**
 * Allow alphanumerics, dot, dash, underscore, space. Rejects
 * everything that could cause YAML escaping issues or shell-metachar
 * surprises if echoed back into a script.
 */
function isSafeProjectName(s: string): boolean {
  if (s.length === 0 || s.length > 128) return false;
  return /^[A-Za-z0-9._\- ]+$/.test(s);
}
